project:
  type: website
  output-dir: docs

website:
  title: "first-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/k1minchae
format:
  html:
    theme:
      light: flatly
      dark: cyborg
    css: styles.css
    # include-after-body: darkmode.js

execute:
  warning: false
  freeze: true
